par(mfcol = c(2,2))

with(s,plot(ftime,Global_active_power,type = "l",ylab = "Global Active Power (kilowatts)",xlab = ""))
s$Sub_metering_1 = as.numeric(as.character(s$Sub_metering_1))
s$Sub_metering_2 = as.numeric(as.character(s$Sub_metering_2))
s$Sub_metering_3 = as.numeric(as.character(s$Sub_metering_3))
with(s,plot(ftime,s$Sub_metering_1,type = "l",ylab = "Energy sub metering",xlab = ""))
lines(ftime, s$Sub_metering_2, col = "red")
lines(ftime, s$Sub_metering_3, col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex = 0.5,lwd=c(2.0,2.0),lty = c(1,1),col = c("black","red","blue"))
with(s,plot(ftime,s$Voltage,type = "l",ylab = "Voltage",xlab = "daytime"))
with(s,plot(ftime,s$Global_reactive_power,type = "l",ylab = "Global_reactive_power",xlab = "daytime"))
dev.copy(png, file = "plot4.png") 
dev.off() 
