s$Sub_metering_1 = as.numeric(as.character(s$Sub_metering_1))
s$Sub_metering_2 = as.numeric(as.character(s$Sub_metering_2))
s$Sub_metering_3 = as.numeric(as.character(s$Sub_metering_3))
with(s,plot(ftime,s$Sub_metering_1,type = "l",ylab = "Energy sub metering",xlab = ""))
lines(ftime, s$Sub_metering_2, col = "red")
lines(ftime, s$Sub_metering_3, col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=c(2.0,2.0),lty = c(1,1),col = c("black","red","blue"))
dev.copy(png, file = "plot3.png") 
dev.off() 